### ISSUE TITLE
vs code can not activate this extend

### ISSUE THREAD

**Issue by LanceAdd** [kataras/vscode-iris#1]
I have installed this extend.when i write code with iris,the vscode tell me that he can't activate the extend because of  missing dependency "lukehoban.go", but i did not find this file.
So, i want to get your help.
vscode version:1.33.0
thanks for your work that help us very much

**Comment by Alsmile** [comment]
+1

**Comment by flytrap** [comment]
+1

**Comment by kataras** [comment]
Hey @shanyujie , @Alsmile , @flytrap sorry for this huge delay, It's **fixed**. Thanks for the report!!
